// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go
/*
Package api holds the domain and transport types that are the single source
of truth for both the Go backend and the TypeScript frontend. TS types are
generated from this file with tygo (see tygo.yaml and `go generate`).
*/

/**
 * ContainerStatus is the friendly, jargon-light state shown in the UI.
 */
export type ContainerStatus = string;
export const StatusRunning: ContainerStatus = "running";
export const StatusStopped: ContainerStatus = "stopped";
export const StatusNeedsAttention: ContainerStatus = "needs_attention";
export const StatusUpdating: ContainerStatus = "updating";
export const StatusMissing: ContainerStatus = "missing";
/**
 * User is an account. Passkey-only; no password ever stored.
 */
export interface User {
  id: string;
  name: string;
  isAdmin: boolean;
  createdAt: number /* int64 */;
}
/**
 * Credential is one registered passkey belonging to a user.
 */
export interface Credential {
  id: string;
  name: string;
  createdAt: number /* int64 */;
}
/**
 * Invite is a single-use, expiring enrollment link.
 */
export interface Invite {
  token: string;
  isAdmin: boolean;
  expiresAt: number /* int64 */;
  usedAt: number /* int64 */;
  url: string;
  /**
   * ForUserName is set on recovery invites: the display name of the existing
   * user this link re-enrolls a passkey for. Empty on normal invites.
   */
  forUserName?: string;
}
/**
 * Container is a single managed or discovered container.
 */
export interface Container {
  id: string;
  name: string;
  containerName: string;
  image: string;
  state: string;
  status: ContainerStatus;
  health: string;
  managed: boolean;
  autoUpdate: boolean;
  updateAvailable: boolean;
  restartCount: number /* int */;
  createdAt: number /* int64 */;
}
/**
 * Stack groups containers by compose project (or manual grouping).
 */
export interface Stack {
  id: string;
  name: string;
  managed: boolean;
  status: ContainerStatus;
  containers: Container[];
}
/**
 * DiskUsage is per-filesystem usage.
 */
export interface DiskUsage {
  mount: string;
  used: number /* uint64 */;
  total: number /* uint64 */;
}
/**
 * HostMetrics is a snapshot of host-level resource use.
 */
export interface HostMetrics {
  cpuPercent: number /* float64 */;
  memUsed: number /* uint64 */;
  memTotal: number /* uint64 */;
  disks: DiskUsage[];
  diskReadBytesPerSec: number /* uint64 */;
  diskWriteBytesPerSec: number /* uint64 */;
}
/**
 * ContainerMetrics is a snapshot of one container's resource use.
 */
export interface ContainerMetrics {
  id: string;
  cpuPercent: number /* float64 */;
  memUsed: number /* uint64 */;
  memLimit: number /* uint64 */;
}
/**
 * MetricsSnapshot is pushed over the WS on an interval.
 */
export interface MetricsSnapshot {
  host: HostMetrics;
  containers: ContainerMetrics[];
  at: number /* int64 */;
}
/**
 * JobProgress reports the lifecycle of a long-running action over the WS.
 */
export interface JobProgress {
  id: string;
  kind: string;
  target: string;
  phase: string;
  message: string;
  done: boolean;
  error: string;
}
/**
 * WSMessageType tags the WS envelope.
 */
export type WSMessageType = string;
export const WSTypeMetrics: WSMessageType = "metrics";
export const WSTypeStacks: WSMessageType = "stacks";
export const WSTypeJob: WSMessageType = "job";
/**
 * WSMessage is the server→client push envelope. Exactly one payload is set.
 */
export interface WSMessage {
  type: WSMessageType;
  metrics?: MetricsSnapshot;
  stacks?: Stack[];
  job?: JobProgress;
}
/**
 * SessionInfo is returned by /auth/me for the current session.
 */
export interface SessionInfo {
  user: User;
  credentials: Credential[];
}
/**
 * CreateInviteRequest asks for a new enrollment link.
 */
export interface CreateInviteRequest {
  isAdmin: boolean;
}
/**
 * EnrollRequest carries the invite token and chosen passkey/user name.
 */
export interface EnrollRequest {
  token: string;
  name: string;
}
/**
 * AdoptRequest adopts a discovered stack into management.
 */
export interface AdoptRequest {
  stackId: string;
}
/**
 * SetAutoUpdateRequest toggles auto-update for a container.
 */
export interface SetAutoUpdateRequest {
  containerId: string;
  autoUpdate: boolean;
}
/**
 * Settings are the mutable app settings.
 */
export interface Settings {
  pollIntervalSeconds: number /* int */;
  autoUpdateDefault: boolean;
  autoUpdateIntervalMinutes: number /* int */;
}
/**
 * APIError is the shape of error responses.
 */
export interface APIError {
  error: string;
}
