// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go
/*
Package api holds the domain and transport types that are the single source
of truth for both the Go backend and the TypeScript frontend. TS types are
generated from this file with tygo (see tygo.yaml and `go generate`).
*/

/**
 * ContainerStatus is the friendly, jargon-light state shown in the UI.
 */
export type ContainerStatus = string;
export const StatusRunning: ContainerStatus = "running";
export const StatusStopped: ContainerStatus = "stopped";
export const StatusNeedsAttention: ContainerStatus = "needs_attention";
export const StatusUpdating: ContainerStatus = "updating";
export const StatusMissing: ContainerStatus = "missing";
/**
 * User is an account. Passkey-only; no password ever stored.
 */
export interface User {
  id: string;
  name: string;
  isAdmin: boolean;
  createdAt: number /* int64 */;
}
/**
 * Credential is one registered passkey belonging to a user.
 */
export interface Credential {
  id: string;
  name: string;
  createdAt: number /* int64 */;
}
/**
 * Invite is a single-use, expiring enrollment link.
 */
export interface Invite {
  token: string;
  isAdmin: boolean;
  expiresAt: number /* int64 */;
  usedAt: number /* int64 */;
  url: string;
  /**
   * ForUserName is set on recovery invites: the display name of the existing
   * user this link re-enrolls a passkey for. Empty on normal invites.
   */
  forUserName?: string;
}
/**
 * Container is a single managed or discovered container.
 */
export interface Container {
  id: string;
  name: string;
  containerName: string;
  image: string;
  state: string;
  status: ContainerStatus;
  health: string;
  managed: boolean;
  autoUpdate: boolean;
  updateAvailable: boolean;
  restartCount: number /* int */;
  createdAt: number /* int64 */;
}
/**
 * Stack groups containers by compose project (or manual grouping).
 */
export interface Stack {
  id: string;
  name: string;
  managed: boolean;
  status: ContainerStatus;
  containers: Container[];
}
/**
 * DiskUsage is per-filesystem capacity usage. Key is the stable visibility key
 * (see DiskItem) so the UI can tie a gauge back to its config toggle.
 */
export interface DiskUsage {
  key: string;
  mount: string;
  used: number /* uint64 */;
  total: number /* uint64 */;
}
/**
 * DiskActivity is one physical device's read/write throughput. Peaks are the
 * highest rates ever recorded for that device, persisted across restarts; the
 * UI colours the current rate against these highwater marks.
 */
export interface DiskActivity {
  key: string;
  device: string;
  /**
   * Label names the volumes backed by this device (e.g. "Main disk"), derived
   * from /proc on Linux. Empty when the device can't be tied to a mount (e.g.
   * macOS synthesized APFS containers); the UI then falls back to Device.
   */
  label: string;
  readBytesPerSec: number /* uint64 */;
  writeBytesPerSec: number /* uint64 */;
  readPeakBytesPerSec: number /* uint64 */;
  writePeakBytesPerSec: number /* uint64 */;
}
/**
 * DiskKind distinguishes the two disconnected views a disk can appear in:
 * capacity is per mount, activity is per physical device.
 */
export type DiskKind = string;
export const DiskCapacity: DiskKind = "capacity";
export const DiskActivityKind: DiskKind = "activity";
/**
 * DiskItem is one configurable entry in the "which disks to show" settings. It
 * covers both a capacity mount and an activity device; Kind says which.
 */
export interface DiskItem {
  key: string;
  kind: DiskKind;
  label: string;
  detail: string;
  shown: boolean;
  defaultShown: boolean;
}
/**
 * HostMetrics is a snapshot of host-level resource use. Disks and DiskActivity
 * carry only the entries the current visibility settings leave shown.
 */
export interface HostMetrics {
  cpuPercent: number /* float64 */;
  memUsed: number /* uint64 */;
  memTotal: number /* uint64 */;
  disks: DiskUsage[];
  diskActivity: DiskActivity[];
}
/**
 * ContainerMetrics is a snapshot of one container's resource use.
 */
export interface ContainerMetrics {
  id: string;
  cpuPercent: number /* float64 */;
  memUsed: number /* uint64 */;
  memLimit: number /* uint64 */;
}
/**
 * MetricsSnapshot is pushed over the WS on an interval.
 */
export interface MetricsSnapshot {
  host: HostMetrics;
  containers: ContainerMetrics[];
  at: number /* int64 */;
}
/**
 * JobProgress reports the lifecycle of a long-running action over the WS.
 */
export interface JobProgress {
  id: string;
  kind: string;
  target: string;
  phase: string;
  message: string;
  done: boolean;
  error: string;
}
/**
 * WSMessageType tags the WS envelope.
 */
export type WSMessageType = string;
export const WSTypeMetrics: WSMessageType = "metrics";
export const WSTypeStacks: WSMessageType = "stacks";
export const WSTypeJob: WSMessageType = "job";
/**
 * WSTypeJobs is the whole job picture, sent once when a client connects: the
 * updates in flight plus the ones that just finished. A client that was away
 * (or was never here) has no other way to learn about an update that started,
 * or finished, without it.
 */
export const WSTypeJobs: WSMessageType = "jobs";
/**
 * WSMessage is the server→client push envelope. Exactly one payload is set.
 */
export interface WSMessage {
  type: WSMessageType;
  metrics?: MetricsSnapshot;
  stacks?: Stack[];
  job?: JobProgress;
  jobs?: JobProgress[];
}
/**
 * SessionInfo is returned by /auth/me for the current session.
 */
export interface SessionInfo {
  user: User;
  credentials: Credential[];
}
/**
 * CreateInviteRequest asks for a new enrollment link.
 */
export interface CreateInviteRequest {
  isAdmin: boolean;
}
/**
 * EnrollRequest carries the invite token and chosen passkey/user name.
 */
export interface EnrollRequest {
  token: string;
  name: string;
}
/**
 * AdoptRequest adopts a discovered stack into management.
 */
export interface AdoptRequest {
  stackId: string;
}
/**
 * SetAutoUpdateRequest toggles auto-update for a container.
 */
export interface SetAutoUpdateRequest {
  containerId: string;
  autoUpdate: boolean;
}
/**
 * Settings are the mutable app settings.
 */
export interface Settings {
  pollIntervalSeconds: number /* int */;
  autoUpdateDefault: boolean;
  autoUpdateIntervalMinutes: number /* int */;
  /**
   * DiskVisibility overrides the default shown/hidden state per disk key. Keys
   * absent here fall back to the built-in heuristic. Applies to all users.
   */
  diskVisibility: { [key: string]: boolean};
}
/**
 * NotificationEvent names a kind of event that can be delivered to the
 * configured notification channels.
 */
export type NotificationEvent = string;
/**
 * EventUpdateApplied fires when an auto-update or a manual update finishes,
 * whether it succeeded or was rolled back.
 */
export const EventUpdateApplied: NotificationEvent = "update_applied";
/**
 * EventUpdateAvailable fires when a newer image appears for a managed
 * container that does not have auto-update enabled.
 */
export const EventUpdateAvailable: NotificationEvent = "update_available";
/**
 * EventContainerStatus fires when a managed container changes status, e.g.
 * starts crash-looping, goes unhealthy, disappears, or recovers.
 */
export const EventContainerStatus: NotificationEvent = "container_status";
/**
 * EventAuth fires on passkey enrollment, logins and other account changes.
 */
export const EventAuth: NotificationEvent = "auth";
/**
 * NotificationConfig is where notifications go and which events are sent.
 */
export interface NotificationConfig {
  /**
   * URLs are Shoutrrr service URLs, one per target, e.g.
   * "discord://token@channel" or "ntfy://ntfy.sh/my-topic". They carry
   * credentials, so this config is admin-only.
   */
  urls: string[];
  /**
   * Events maps each NotificationEvent to whether it is delivered. Events
   * absent from the map are treated as enabled.
   */
  events: { [key: NotificationEvent]: boolean};
  /**
   * EnvManaged reports that the config comes from VEERY_NOTIFY_URLS and so
   * cannot be edited through the UI.
   */
  envManaged: boolean;
}
/**
 * TestNotificationRequest sends a test message. URLs, when non-empty, are used
 * instead of the saved ones so a channel can be checked before it is saved.
 */
export interface TestNotificationRequest {
  urls: string[];
}
/**
 * SetDiskVisibilityRequest updates which disks are shown, for all users.
 */
export interface SetDiskVisibilityRequest {
  visibility: { [key: string]: boolean};
}
/**
 * APIError is the shape of error responses.
 */
export interface APIError {
  error: string;
}
