// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go
/*
Package api holds the domain and transport types that are the single source
of truth for both the Go backend and the TypeScript frontend. TS types are
generated from this file with tygo (see tygo.yaml and `go generate`).
*/

/**
 * ContainerStatus is the friendly, jargon-light state shown in the UI.
 */
export type ContainerStatus = string;
export const StatusRunning: ContainerStatus = "running";
export const StatusStopped: ContainerStatus = "stopped";
export const StatusNeedsAttention: ContainerStatus = "needs_attention";
export const StatusUpdating: ContainerStatus = "updating";
export const StatusMissing: ContainerStatus = "missing";
/**
 * User is an account. Passkey-only; no password ever stored.
 */
export interface User {
  id: string;
  name: string;
  isAdmin: boolean;
  createdAt: number /* int64 */;
}
/**
 * Credential is one registered passkey belonging to a user.
 */
export interface Credential {
  id: string;
  name: string;
  createdAt: number /* int64 */;
}
/**
 * Invite is a single-use, expiring enrollment link.
 */
export interface Invite {
  token: string;
  isAdmin: boolean;
  expiresAt: number /* int64 */;
  usedAt: number /* int64 */;
  url: string;
  /**
   * ForUserName is set on recovery invites: the display name of the existing
   * user this link re-enrolls a passkey for. Empty on normal invites.
   */
  forUserName?: string;
}
/**
 * Container is a single managed or discovered container.
 */
export interface Container {
  id: string;
  name: string;
  containerName: string;
  image: string;
  state: string;
  status: ContainerStatus;
  health: string;
  managed: boolean;
  autoUpdate: boolean;
  updateAvailable: boolean;
  restartCount: number /* int */;
  createdAt: number /* int64 */;
}
/**
 * Stack groups containers by compose project (or manual grouping).
 */
export interface Stack {
  id: string;
  name: string;
  managed: boolean;
  status: ContainerStatus;
  containers: Container[];
}
/**
 * DiskUsage is per-filesystem capacity usage. Key is the stable visibility key
 * (see DiskItem) so the UI can tie a gauge back to its config toggle.
 */
export interface DiskUsage {
  key: string;
  mount: string;
  used: number /* uint64 */;
  total: number /* uint64 */;
}
/**
 * DiskActivity is one physical device's read/write throughput. Peaks are the
 * highest rates ever recorded for that device, persisted across restarts; the
 * UI colours the current rate against these highwater marks.
 */
export interface DiskActivity {
  key: string;
  device: string;
  /**
   * Label names the volumes backed by this device (e.g. "Main disk"), derived
   * from /proc on Linux. Empty when the device can't be tied to a mount (e.g.
   * macOS synthesized APFS containers); the UI then falls back to Device.
   */
  label: string;
  readBytesPerSec: number /* uint64 */;
  writeBytesPerSec: number /* uint64 */;
  readPeakBytesPerSec: number /* uint64 */;
  writePeakBytesPerSec: number /* uint64 */;
}
/**
 * DiskKind distinguishes the two disconnected views a disk can appear in:
 * capacity is per mount, activity is per physical device.
 */
export type DiskKind = string;
export const DiskCapacity: DiskKind = "capacity";
export const DiskActivityKind: DiskKind = "activity";
/**
 * DiskItem is one configurable entry in the "which disks to show" settings. It
 * covers both a capacity mount and an activity device; Kind says which.
 */
export interface DiskItem {
  key: string;
  kind: DiskKind;
  label: string;
  detail: string;
  shown: boolean;
  defaultShown: boolean;
}
/**
 * HostMetrics is a snapshot of host-level resource use. Disks and DiskActivity
 * carry only the entries the current visibility settings leave shown.
 */
export interface HostMetrics {
  cpuPercent: number /* float64 */;
  memUsed: number /* uint64 */;
  memTotal: number /* uint64 */;
  disks: DiskUsage[];
  diskActivity: DiskActivity[];
  /**
   * Mdadm carries Linux software RAID array health. Nil/empty when the host
   * has no md arrays or /proc and /sys aren't mounted in; the UI hides the
   * panel then.
   */
  mdadm: MdArray[];
}
/**
 * MdArrayState is the health rollup for a Linux software RAID (mdadm) array.
 */
export type MdArrayState = string;
export const MdHealthy: MdArrayState = "healthy";
export const MdDegraded: MdArrayState = "degraded";
export const MdRecovering: MdArrayState = "recovering"; // resync/recover/reshape/check in progress
export const MdFailed: MdArrayState = "failed";
/**
 * MdSyncAction is the array's current sync operation, mirroring the sysfs
 * sync_action value.
 */
export type MdSyncAction = string; // "idle" | "check" | "resync" | "recover" | "reshape"
/**
 * MdArray is one Linux software RAID array's health, read from /proc/mdstat and
 * sysfs. Empty on hosts without RAID (or without /proc and /sys mounted in), so
 * the UI hides the panel.
 */
export interface MdArray {
  name: string; // md0
  level: string; // raid1
  state: MdArrayState;
  devicesTotal: number /* int */;
  devicesUp: number /* int */;
  members: MdMember[];
  syncAction: MdSyncAction; // idle when no scan running
  syncPercent: number /* float64 */; // 0 when idle
  syncSpeedKBs: number /* uint64 */; // 0 when idle
  syncFinish: string; // e.g. "189.2min", "" when idle
  mismatchCnt: number /* uint64 */;
  /**
   * LastScanAt is the Unix time (seconds) of the last data-scrub Veery saw
   * finish on this array. The kernel keeps no such timestamp, so Veery records
   * it when it observes a check return to idle. 0 means unknown (none seen yet).
   */
  lastScanAt: number /* int64 */;
}
/**
 * MdadmSchedule is a per-array automatic data-scrub schedule.
 */
export interface MdadmSchedule {
  /**
   * RRule is an iCal RRULE (RFC 5545) describing when to scrub, e.g.
   * "FREQ=WEEKLY;BYDAY=SU;BYHOUR=20;BYMINUTE=0" for Sundays at 8PM. It is
   * evaluated in the server's local timezone (set TZ to control it).
   */
  rrule: string;
  /**
   * Enabled gates the schedule without discarding the rule.
   */
  enabled: boolean;
}
/**
 * MdadmScheduleConfig maps a RAID array name (e.g. "md0") to its scrub schedule.
 */
export interface MdadmScheduleConfig {
  schedules: { [key: string]: MdadmSchedule};
}
/**
 * MdMember is one member device of an array and whether it is up.
 */
export interface MdMember {
  device: string; // sdb1
  up: boolean;
}
/**
 * ContainerMetrics is a snapshot of one container's resource use.
 */
export interface ContainerMetrics {
  id: string;
  cpuPercent: number /* float64 */;
  memUsed: number /* uint64 */;
  memLimit: number /* uint64 */;
}
/**
 * MetricsSnapshot is pushed over the WS on an interval.
 */
export interface MetricsSnapshot {
  host: HostMetrics;
  containers: ContainerMetrics[];
  at: number /* int64 */;
}
/**
 * JobProgress reports the lifecycle of a long-running action over the WS.
 */
export interface JobProgress {
  id: string;
  kind: string;
  target: string;
  phase: string;
  message: string;
  done: boolean;
  error: string;
}
/**
 * WSMessageType tags the WS envelope.
 */
export type WSMessageType = string;
export const WSTypeMetrics: WSMessageType = "metrics";
export const WSTypeStacks: WSMessageType = "stacks";
export const WSTypeJob: WSMessageType = "job";
/**
 * WSTypeJobs is the whole job picture, sent once when a client connects: the
 * updates in flight plus the ones that just finished. A client that was away
 * (or was never here) has no other way to learn about an update that started,
 * or finished, without it.
 */
export const WSTypeJobs: WSMessageType = "jobs";
/**
 * WSMessage is the server→client push envelope. Exactly one payload is set.
 */
export interface WSMessage {
  type: WSMessageType;
  metrics?: MetricsSnapshot;
  stacks?: Stack[];
  job?: JobProgress;
  jobs?: JobProgress[];
}
/**
 * SessionInfo is returned by /auth/me for the current session.
 */
export interface SessionInfo {
  user: User;
  credentials: Credential[];
}
/**
 * CreateInviteRequest asks for a new enrollment link.
 */
export interface CreateInviteRequest {
  isAdmin: boolean;
}
/**
 * EnrollRequest carries the invite token and chosen passkey/user name.
 */
export interface EnrollRequest {
  token: string;
  name: string;
}
/**
 * AdoptRequest adopts a discovered stack into management.
 */
export interface AdoptRequest {
  stackId: string;
}
/**
 * SetAutoUpdateRequest toggles auto-update for a container.
 */
export interface SetAutoUpdateRequest {
  containerId: string;
  autoUpdate: boolean;
}
/**
 * Settings are the mutable app settings.
 */
export interface Settings {
  pollIntervalSeconds: number /* int */;
  autoUpdateDefault: boolean;
  autoUpdateIntervalMinutes: number /* int */;
  /**
   * DiskVisibility overrides the default shown/hidden state per disk key. Keys
   * absent here fall back to the built-in heuristic. Applies to all users.
   */
  diskVisibility: { [key: string]: boolean};
}
/**
 * NotificationEvent names a kind of event that can be delivered to the
 * configured notification channels.
 */
export type NotificationEvent = string;
/**
 * EventUpdateApplied fires when an auto-update or a manual update finishes,
 * whether it succeeded or was rolled back.
 */
export const EventUpdateApplied: NotificationEvent = "update_applied";
/**
 * EventUpdateAvailable fires when a newer image appears for a managed
 * container that does not have auto-update enabled.
 */
export const EventUpdateAvailable: NotificationEvent = "update_available";
/**
 * EventContainerStatus fires when a managed container changes status, e.g.
 * starts crash-looping, goes unhealthy, stops, or recovers.
 */
export const EventContainerStatus: NotificationEvent = "container_status";
/**
 * EventContainerMissing fires when a managed container is removed from the
 * host. It is separate from EventContainerStatus because removing one is
 * usually the user's own doing (a compose file edit, a compose down), so it
 * is the event most worth turning off on a host that changes often.
 */
export const EventContainerMissing: NotificationEvent = "container_missing";
/**
 * EventContainerAdopted fires when Veery takes over a container that
 * appeared in a stack it already manages, which it does on its own.
 */
export const EventContainerAdopted: NotificationEvent = "container_adopted";
/**
 * EventAuth fires on passkey enrollment, logins and other account changes.
 */
export const EventAuth: NotificationEvent = "auth";
/**
 * EventRaidScanStarted fires when a data-scrub (check) begins on a RAID
 * array, whoever started it — Veery's scheduler, a host cron, or a manual
 * mdadm command — since it is detected as a state transition.
 */
export const EventRaidScanStarted: NotificationEvent = "raid_scan_started";
/**
 * EventRaidScanFinished fires when a data-scrub finishes and the array
 * returns to idle.
 */
export const EventRaidScanFinished: NotificationEvent = "raid_scan_finished";
/**
 * EventRaidUnhealthy fires when a RAID array goes degraded or failed, and
 * again when it recovers to healthy.
 */
export const EventRaidUnhealthy: NotificationEvent = "raid_unhealthy";
/**
 * EventRaidDiskOffline fires when a member disk of a RAID array drops out,
 * and again when it comes back.
 */
export const EventRaidDiskOffline: NotificationEvent = "raid_disk_offline";
/**
 * NotificationConfig is where notifications go and which events are sent.
 */
export interface NotificationConfig {
  /**
   * URLs are Shoutrrr service URLs, one per target, e.g.
   * "discord://token@channel" or "ntfy://ntfy.sh/my-topic". They carry
   * credentials, so this config is admin-only.
   */
  urls: string[];
  /**
   * Events maps each NotificationEvent to whether it is delivered. Events
   * absent from the map are treated as enabled.
   */
  events: { [key: NotificationEvent]: boolean};
  /**
   * EnvManaged reports that the config comes from VEERY_NOTIFY_URLS and so
   * cannot be edited through the UI.
   */
  envManaged: boolean;
}
/**
 * TestNotificationRequest sends a test message. URLs, when non-empty, are used
 * instead of the saved ones so a channel can be checked before it is saved.
 */
export interface TestNotificationRequest {
  urls: string[];
}
/**
 * SetDiskVisibilityRequest updates which disks are shown, for all users.
 */
export interface SetDiskVisibilityRequest {
  visibility: { [key: string]: boolean};
}
/**
 * APIError is the shape of error responses.
 */
export interface APIError {
  error: string;
}
